// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ORT_PORTAL_ABOGADOS.Context;

#nullable disable

namespace ORT_PORTAL_ABOGADOS.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20251118045104_apiRegistro")]
    partial class apiRegistro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ORT_PORTAL_ABOGADOS.Models.Abogado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<int>("Folio")
                        .HasColumnType("int");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tomo")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Abogados");
                });

            modelBuilder.Entity("ORT_PORTAL_ABOGADOS.Models.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AbogadoId")
                        .HasColumnType("int");

                    b.Property<int?>("AbogadoId1")
                        .HasColumnType("int");

                    b.Property<string>("ApellidoCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("bit");

                    b.Property<int>("IdAbogado")
                        .HasColumnType("int");

                    b.Property<string>("MailCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AbogadoId");

                    b.HasIndex("AbogadoId1");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("ORT_PORTAL_ABOGADOS.Models.Consulta", b =>
                {
                    b.HasOne("ORT_PORTAL_ABOGADOS.Models.Abogado", null)
                        .WithMany("ConsultasActivas")
                        .HasForeignKey("AbogadoId");

                    b.HasOne("ORT_PORTAL_ABOGADOS.Models.Abogado", null)
                        .WithMany("SolicitudesPendientes")
                        .HasForeignKey("AbogadoId1");
                });

            modelBuilder.Entity("ORT_PORTAL_ABOGADOS.Models.Abogado", b =>
                {
                    b.Navigation("ConsultasActivas");

                    b.Navigation("SolicitudesPendientes");
                });
#pragma warning restore 612, 618
        }
    }
}
